# Site settings
title: "Nikas Praninskas"
email: nikaspran@gmail.com
author: Nikas Praninskas
description: "A blog about beautiful code, web development and technology"
github_username: nikaspran
twitter_username: nikaspran
baseurl: ""
url: "http://nikas.praninskas.com"
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
sass:
  compressed: true

gems:
  - jekyll-paginate
  - jekyll-redirect-from

kramdown:
  input: GFM
  syntax_highlighter: rouge
