# Site settings
title: "Nikas Praninskas"
email: nikaspran@gmail.com
author: Nikas Praninskas
description: "A blog about beautiful code, web development and technology"
github_username: nikaspran
twitter_username: nikaspran
baseurl: ""
url: "http://nikas.praninskas.com"
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
